# --- DRACULA & UI ---
set colorscheme dracula
set draw_borders true

# --- GIT & IMAGES ---
set vcs_aware true
set preview_images true
set preview_images_method ueberzug

# --- HELGAARD'S FAST TRAVEL ---
# Press 'gd' to jump to Projects
map gd cd /mnt/storage/Projects
# Press 'gs' to jump to Dotfiles
map gs cd /mnt/storage/dotfiles
